package aandrosov.funcatfacts.app.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF904B3C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFDAD3)
val onPrimaryContainerLight = Color(0xFF3A0A03)
val secondaryLight = Color(0xFF775750)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDAD3)
val onSecondaryContainerLight = Color(0xFF2C1510)
val tertiaryLight = Color(0xFF6E5D2E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFF9E0A6)
val onTertiaryContainerLight = Color(0xFF241A00)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF231917)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFFFFFFFF)
val surfaceVariantLight = Color(0xFFF5DDD9)
val onSurfaceVariantLight = Color(0xFFFFFFFF)
val outlineLight = Color(0xFF85736F)
val outlineVariantLight = Color(0xFFD8C2BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392E2C)
val inverseOnSurfaceLight = Color(0xFFFFEDE9)
val inversePrimaryLight = Color(0xFFFFB4A4)
val surfaceDimLight = Color(0xFFE8D6D3)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFF8F7263)
val surfaceContainerLowLight = Color(0xFFAF8B79)
val surfaceContainerLight = Color(0xFFBE9782)
val surfaceContainerHighLight = Color(0xFFF5DDD9)
val surfaceContainerHighestLight = Color(0xFFF5DDD9)




